config/routes.rb
Rails.application.routes.draw do
  
  root :to=>"users#new"

  resources :roles do
    get :add_member,:on=>:member
    get :del_member,:on=>:member
    get :mlist,:on=>:member
    get :get_role,:on=>:collection
    get :user_list,:on=>:collection
    post :process_set,:on=>:collection
    get :assign,:on=>:collection
    get :company,:on=>:collection
    get :get_max_service,:on=>:collection
    get :set_max_service,:on=>:collection
    get :set_session_log,:on=>:collection
    get :del_session_log,:on=>:collection
    get :get_customer_service,:on=>:collection
  end

  resources :guests do
    get :reg_guest,:on=>:collection
    get :get_guests,:on=>:collection
    get :set_trail,:on=>:collection
    get :get_trail,:on=>:collection
    get :get_all_guests,:on=>:collection
  end

  resources :tasks do
    get :create_question,:on=>:collection
    get :get_tasks,:on=>:collection
    get :get_task_count,:on=>:collection
    get :question,:on=>:collection
    get :answer,:on=>:collection
    get :append_answer,:on=>:collection
    get :finish,:on=>:collection
  end

  resources :users do
    post :login,:on=>:collection
    get :logout,:on=>:collection
  end

  resources :customer_info_tasks do
    get :create_instance,:on=>:collection
    get :pass,:on=>:collection
    get :eventlogs,:on=>:collection
    get :process_list,:on=>:collection
    get :apply,:on=>:collection
    get :fail,:on=>:collection
    get :get_tasks,:on=>:collection
  end
  resources :roles_users

end

app/models/task.rb
class Task < ActiveRecord::Base
  state_machine :initial => :init do
    after_transition :event_log
    before_transition :update_index
    event :created do  
      transition :init => :created
    end

    event :question do  
      transition :created => :question
    end

    event :answer do
      transition :question => :answered
    end

    event :append_answer do
      transition :answered => :answered
    end

    event :finish do
      transition :answered => :finished
    end

  end

  def attachments
    BpmAttachment.where(:process_id=>self.id)
  end

  def update_index
    self.index = self.index + 1
    self.save
  end

  def event_log(transition)
  	event = EventLog.new
  	event.task_id = self.id
  	event.role_id = self.role_id
    event.index = self.index
  	event.username = self.username
  	event.operation = transition.event
    event.from = transition.from
    event.to = transition.to
  	event.save
  end
end

app/controllers/tasks_controller.rb
#encoding: utf-8
class TasksController < ApplicationController
  before_filter :authorize_user!,:except => [:create_question,:question,:answer,:get_tasks,:finish,:append_answer]
  # GET /roles
  # GET /roles.json
  def index
    @tasks = CustomerInfoTask.paginate(:page => params[:page], :per_page => 20).order("created_at DESC")
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  def process_set
    
  end

  def get_tasks
    @role_id = Role.find_by_role_code(params[:role_code]).id
    @tasks = Task.where(:role_id=>@role_id,:username=>params[:username])
  end

  def process_list
    @ids = CustomerInfoTask.pluck(:id)
    render :json => {"ids"=>@ids}
  end

  def eventlogs
    @events = EventLog.where(:task_id=>params[:task_id]).paginate(:page => params[:page], :per_page => 20).order("created_at DESC")
  end

  def create_question
    task = Task.new
    task.username = params[:username]
    @role = check_role_exist(params[:role_code])
    task.role_id = @role.id
    task.task_type = params[:type]
    task.save
    task.created
    if !params[:content].blank?
      @attach =  BpmAttachment.where(:process_id=>params[:task_id],:index=>task.index)
      if @attach.blank?
        attachment = BpmAttachment.new
        attachment.process_id = task.id
        attachment.process_type = task.task_type
        attachment.index = task.index
        attachment.attachment_type = "text"
        attachment.content = params[:content]
        attachment.save
      end
      if !params[:file].blank?
        attachment = BpmAttachment.new
        attachment.process_id = task.id
        attachment.process_type = task.task_type
        attachment.index = task.index
        attachment.attachment_type = "file"
        attachment.content = params[:file]
        attachment.save
      end
    end
    render :json => {"task_id"=>task.id}
  end

  def question
    @task = Task.find(params[:task_id])
    @role = check_role_exist(params[:role_code])
    @task.role_id = @role.id
    @task.username = params[:username]
    @task.question
    if !params[:content].blank?
      @attach =  BpmAttachment.where(:process_id=>params[:task_id],:index=>@task.index)
      if @attach.blank?
        attachment = BpmAttachment.new
        attachment.process_id = @task.id
        attachment.process_type = @task.task_type
        attachment.index = @task.index
        attachment.attachment_type = "text"
        attachment.content = params[:content]
        attachment.save
      end
      if !params[:file].blank?
        attachment = BpmAttachment.new
        attachment.process_id = task.id
        attachment.process_type = task.task_type
        attachment.index = task.index
        attachment.attachment_type = "file"
        attachment.content = params[:file]
        attachment.save
      end
    end
    render :json => {"result"=>"t"}
  end

  def finish
    @task = Task.find(params[:task_id])
    @role = check_role_exist(params[:role_code])
    @task.role_id = @role.id
    @task.username = params[:username]
    @task.finish
    render :json => {"result"=>"t"}
  end

  def answer
    @task = Task.find(params[:task_id])
    @role = check_role_exist(params[:role_code])
    @task.role_id = @role.id
    @task.username = params[:username]
    @task.answer

    if !params[:content].blank?
      @attach =  BpmAttachment.where(:process_id=>params[:task_id],:index=>@task.index)
      if @attach.blank?
        attachment = BpmAttachment.new
        attachment.process_id = @task.id
        attachment.index = @task.index
        attachment.process_type = @task.task_type
        attachment.attachment_type = "text"
        attachment.content = params[:content]
        attachment.save
      end
      if !params[:file].blank?
        attachment = BpmAttachment.new
        attachment.process_id = task.id
        attachment.process_type = task.task_type
        attachment.index = task.index
        attachment.attachment_type = "file"
        attachment.content = params[:file]
        attachment.save
      end
    end
    render :json => {"result"=>"t"}
  end


  def append_answer
    @task = Task.find(params[:task_id])
    @role = check_role_exist(params[:role_code])
    @task.role_id = @role.id
    @task.username = params[:username]
    @task.append_answer

    if !params[:content].blank?
      @attach =  BpmAttachment.where(:process_id=>params[:task_id],:index=>@task.index)
      if @attach.blank?
        attachment = BpmAttachment.new
        attachment.process_id = @task.id
        attachment.index = @task.index
        attachment.process_type = @task.task_type
        attachment.attachment_type = "text"
        attachment.content = params[:content]
        attachment.save
      end
      if !params[:file].blank?
        attachment = BpmAttachment.new
        attachment.process_id = task.id
        attachment.process_type = task.task_type
        attachment.index = task.index
        attachment.attachment_type = "file"
        attachment.content = params[:file]
        attachment.save
      end
    end
    render :json => {"result"=>"t"}
  end

  def check_role_exist(key)
    @role = Role.find_by_role_code(key)
    if @role.blank?
      render :json => {:result=>false,:desc=>"流程角色还没有创建."}
      return
    end
    return @role
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/views/tasks/_bpm_form.html.erb
<%= form_for :role,:url=>process_set_roles_path,:method=>:post,:html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :content, "流程列表", :class => "control-label" %>
    <div class="controls">
      <%=f.select :process_type,{"客户修改流程"=>"1"},{:include_blank=>"请选择"},{:id=>"bpm"}%>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :content, "流程id", :class => "control-label" %>
    <div class="controls">
    <%=f.select :process_id,{},{:include_blank=>"请选择"},{:id=>"instance_list" }%>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :content, "组织列表", :class => "control-label" %>
    <div class="controls">
    <%=f.select :roles_id,@role_list,{:include_blank=>"请选择"},{:id=>"role_list" }%>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :content, "用户列表", :class => "control-label" %>
    <div class="controls">
    <%=f.select :username,{},{:include_blank=>"请选择"},{:id=>"user_list" }%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                roles_path, :class => 'btn' %>
  </div>
<% end %>
<script type="text/javascript">
  $("#bpm").change(function(){
    var bpm_type = $(this).val();
    var url = "";
    var params = {};
    if(bpm_type=="1")
    {
      url = "/customer_info_tasks/process_list";
    }
    $.ajax(url,{
      type: "GET",
      data: params,
      success: function(res){
        $("#instance_list").empty();
        var id_array = res.ids;
        for(var i=0;i<id_array.length;i++)
        {
          $("#instance_list").append("<option value='"+id_array[i]+"'>"+id_array[i]+"</option>");
        }
      }
    });
  });

  $("#role_list").change(function(){
    var role_id = $(this).val();
    var params = {role_id:role_id};
    var url = "/roles/user_list";
    $.ajax(url,{
      type: "GET",
      data: params,
      success: function(res){
        $("#user_list").empty();
        var id_array = res.usernames;
        for(var i=0;i<id_array.length;i++)
        {
          $("#user_list").append("<option value='"+id_array[i]+"'>"+id_array[i]+"</option>");
        }
      }
    });
  });
</script>

app/views/tasks/_form.html.erb
<%= form_for @role, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :role_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :role_code, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :role_type, "组织类型", :class => "control-label" %>
    <div class="controls">
    <%=f.select :role_type,{"标准"=>0,"流程"=>1},{:include_blank=>"请选择"},{:id=>"role_type_list" }%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                roles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/_sub_form.html.erb
<%= form_for @role_user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :role_id, :class => 'control-label' %>
    <div class="controls">
      <%=@role.name%>
      <%= f.text_field :role_id,:value=>@role.id, :class => 'text_field hidden' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
    <%=f.select :username,User.all.collect{|p| [p.username,p.username] },{:include_blank=>"请选择"},{:id=>"city" }%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                roles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/add_member.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1>新增人员</h1>
</div>
<%= render :partial => 'sub_form' %>

app/views/tasks/edit.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1>组织列表</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:role_key) %></th>
      <th><%= model_class.human_attribute_name(:role_type) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= link_to role.id, role_path(role) %></td>
        <td><a href="/roles/<%=role.id%>/mlist"><%= role.name %></a></td>
        <td><%= role.role_code %></td>
        <td><%= role.role_type_name %></td>
        <td>
          <%= link_to "新增人员",
                      add_member_role_path(role), :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_role_path(role), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      role_path(role),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_role_path,
            :class => 'btn btn-primary' %>

app/views/tasks/mlist.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1>组织列表</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>用户名</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @rusers.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to "删除",
                      del_member_role_path(:user_id=>user.id), :class => 'btn btn-mini' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @role.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              roles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_role_path(@role), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              role_path(@role),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>